version: "2.3"

services:

  pg:
    image: postgres:13.4
    restart: always
    mem_limit: 700M
    environment:
      POSTGRES_PASSWORD: "Iz10mtRj59"
    ports:
      - "12218:5432"
    command:
      - "docker-entrypoint.sh"
      - "-c"
      - "max-connections=800"